#!/usr/bin/env escript
%% -*- erlang -*-
%%! -pa ebin

main([]) -> usage();
main(Xs) ->
    Seed = now(),
    io:format("Initializing random with seed: ~p~n", [Seed]),
    random:seed(now()),
    run(Xs).

usage() -> io:format("Usage: ~s [1|2|3|...]~n", [escript:script_name()]).

run([X|Xs]) -> test(X), run(Xs);
run([]) -> io:format("Done.~n").

test("1") -> test_1();
test("2") -> test_2();
test("3") -> test_3();
test("4") -> test_4();
test(X) -> io:format("Unknown test: ~p~n", [X]).


%% 6.1
test_1() ->
    io:format("6.1 simple neuron test~n"),
    N = enn_node:new(node1, purelin, -1),
    ok = enn_node:add_source(N, self(), random),
    ok = enn_node:add_target(N, self()),
    ok = enn_node:activate(N, 1),
    receive
        {N, activity, A} ->
            io:format("Output: ~p~n", [A])
    after
        1000 ->
            io:format("No activity!~n")
    end.

%% 6.2
test_2() ->
    io:format("6.2 simple nn test~n"),
    {ok, _Network} =
        enn_network:create(
          #{
             sensors => [self()],
             actuators => [self()],
             %% 1 layer with a single node
             layers => [[#{ id => node1, af => purelin, thld => -1}]]
           }),
    Node = receive {N, target} -> N end,
    io:format("activate node ~p~n", [Node]),
    enn_node:activate(Node, random),
    receive
        {Node, activity, A} ->
            io:format("got node activity: ~p~n", [A])
    end.

test_3() ->
    io:format("6.2 simple nn test, Mk-II~n"),
    {ok, NN} =
        enn_network:create(
          #{
             sensors => [{enn_sensor, rng, []}],
             actuators => [{enn_actuator, stdout, []}],
             %% 1 layer with a single node
             layers => [[#{ id => node1, af => purelin, thld => -1}]]
           }),
    [S] = maps:get(sensors, NN),
    S ! update,
    receive after 10 -> ok end.

%% 6.6
test_4() ->
    io:format("6.6 genotype <-> phenotype mapping~n"),
    {ok, PhenoType} =
        enn_network:create(
          #{
             sensors => [{enn_sensor, rng, []}],
             actuators => [{enn_actuator, stdout, []}],
             %% 3 layers with 1, 3, 1 nodes per layer
             layers => [1, 3, 1],
             node_template => #{ af => purelin, thld => -1 }
           }),
    {ok, GenoType} = enn_network:backup(PhenoType),
    io:format("PhenoType: ~p~nGenoType: ~p~n", [PhenoType, GenoType]).
